describe('login', () => {
    it('standard user', ()=> {
        cy.visit('https://saucedemo.com/')
        cy.title().should('equal', 'Swag Labs')
        cy.get('[data-test="username"]').should('be.visible').and('be.empty').type('locked_out_user')
        cy.get('[data-test="password"]').should('be.visible').and('be.empty').type('secret_sauce')
        cy.wait(5000)
         cy.get('[data-test="login-button"]').should('be.visible').click()
         cy.screenshot()
         cy.visit('https://saucedemo.com/')
         cy.get('[data-test="username"]').should('be.visible').and('be.empty').type('problem_user')
         cy.get('[data-test="password"]').should('be.visible').and('be.empty').type('secret_sauce')
         cy.wait(5000)
         cy.screenshot()
         cy.get('[data-test="login-button"]').should('be.visible').click()
          cy.visit('https://saucedemo.com/')
        cy.get('[data-test="username"]').should('be.visible').and('be.empty').type('standard_user')
        cy.get('[data-test="password"]').should('be.visible').and('be.empty').type('secret_sauce')
        cy.wait(5000)
        cy.screenshot()
        cy.get('[data-test="login-button"]').should('be.visible').click()
        cy.wait(5000)
        cy.contains('Products').should('be.visible')
        cy.get('[data-test="inventory-container"]').should('exist')
        cy.get('[data-test="product-sort-container"]').should('exist')
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('[data-test="remove-sauce-labs-onesie"]').should('be.visible').click()
        cy.wait(2000)
        cy.get('[data-test="shopping-cart-link"]').should('be.visible').click()
        cy.get('[data-test="checkout"]').should('be.visible').click()
        cy.wait(5000)
        cy.screenshot()
        cy.get('[data-test="firstName"]').should('be.visible').and('be.empty').type('john')
        cy.wait(2000)
        cy.get('[data-test="lastName"]').should('be.visible').and('be.empty').type('doe')
        cy.wait(2000)
        cy.get('[data-test="postalCode"]').should('be.visible').and('be.empty').type('12345')
        cy.wait(5000)
        cy.get('[data-test="continue"]').click()
        cy.wait(2000)
        cy.get('[data-test="finish"]').click()
        cy.wait(2000)
        cy.screenshot()
        cy.get('[data-test="back-to-products"]').should('be.visible').click()
        cy.get('.bm-burger-button').should('be.visible').and('be.not.empty').click()
        cy.get('[data-test="logout-sidebar-link"]').should('be.visible').click()
        
        
        

        
    })
})