describe('LOGIN',() => {
    it ('standard user',() => {
        cy .visit('https://saucedemo.com/')
        cy.title().should('equal','Swag Labs')
        cy.get('.login_logo').should('be.visible')
        cy.get('#user-name').should('be.visible').and('be.empty').type('standard_user')
        cy.wait(5000)
        cy.get('#password').should('be.visible').and('be.empty').type('secret_sauce')
        cy.wait(10000)
        cy.screenshot()
        cy.get('.submit-button').should('be.visible').click()
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#add-to-cart-sauce-labs-bike-light').click()
        cy.get('.shopping_cart_link').click()
        cy.get('#continue-shopping').click()
        cy.contains('Products').should('be.visible')
        cy.get('.inventory_list').should('exist')
        cy.get('.inventory_item').should('have.length.greaterThan', 5).and('not.be.empty')
        cy.screenshot()
    })
})